name: docker_deploy
on:
  push:
    tags:
      - "*" # eg 1.0.2-alpine-13
jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: satackey/action-js-inline@v0.0.2
        id: parse
        with:
          script: |
            const core = require('@actions/core')
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0]
            const dir = tag.split('-').splice(1).join('-').replace('-','/')
            const arch=dir.split('/')[0]
            let tags=tag
            if(arch=='alpine') tags=tags+',latest'
            tags=tags+',latest-'+tag.split('-').splice(1).join('-')
            core.info(`ref:${process.env.GITHUB_REF},dir:${dir},tag:${tag},tags:${tags}`)
            core.setOutput('tag', tag)
            core.setOutput('dir', dir)
            core.setOutput('tags', tags)
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/setup-buildx-action@v1
        id: buildx
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ${{ steps.parse.outputs.dir }}
          # file: ./Dockerfile # maybe not needed
          push: true
          tags: ${{ steps.parse.outputs.tags }}
      - name: Image digest
        run: echo ${{ github.ref }} of ${{ steps.parse.outputs.tag }} build as ${{ steps.docker_build.outputs.digest }}`

